// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArRef_PafQT991FBuZ6-5yyFBNi_SDPWA',
    appId: '1:597252678857:web:c78c876c5b7b279947d918',
    messagingSenderId: '597252678857',
    projectId: 'restboxd',
    authDomain: 'restboxd.firebaseapp.com',
    storageBucket: 'restboxd.appspot.com',
    measurementId: 'G-W34RD9G34V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbUob9IHDxzEXpZO_8262xoXfkyLm9Kng',
    appId: '1:597252678857:android:0985501c7a176dd547d918',
    messagingSenderId: '597252678857',
    projectId: 'restboxd',
    storageBucket: 'restboxd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZpggGOtXVbjUdsWtyTBbZs6uCo29Hf_A',
    appId: '1:597252678857:ios:69f42c7d68b12dcb47d918',
    messagingSenderId: '597252678857',
    projectId: 'restboxd',
    storageBucket: 'restboxd.appspot.com',
    iosClientId: '597252678857-mit8mnfaqih1hpdsiioothpg9dqjdv5b.apps.googleusercontent.com',
    iosBundleId: 'com.restboxd.app',
  );
}
